# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hey Qiita' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hey Qiita
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SnapKit'
  pod 'AlamofireImage'
  pod 'KRProgressHUD'
  pod 'Down'
  pod 'KeychainAccess'

  target 'Hey QiitaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'Hey QiitaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
